apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hgb-{{ .Values.hgb-app.metadata.name }} #helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.hgb-app.spec.destination.namespace }}
    server: {{ .Values.hgb-app.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/SidReizend/Guestbook.git
    targetRevision: {{ .Values.hgb-app.spec.source.targetRevision }}

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
