apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"registries.conf":"registries:\n  - name: gcr\n    api_url: https://gcr.io\n    prefix: gcr.io\n    credentials: gcr-secret\n","repositories":"- url: git@github.com:SidReize>
data:
  registries.conf: |
    registries:
      - name: gcr
        api_url: https://gcr.io
        prefix: gcr.io
        credentials:
          type: pullsecret
          pullsecret: argocd/gcr-secret
  repositories: |
    - url: git@github.com:SidReizend/Guestbook.git
      sshPrivateKeySecret:
        name: git-creds
        key: sshPrivateKey
