apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-appd
  namespace: argocd
  annotations:
    # Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: <private-registry-url>/<project>/httpbin
    argocd-image-updater.argoproj.io/write-back-method: git  # Update Git with the new image tag
    argocd-image-updater.argoproj.io/image-update-strategy: latest  # Always track the latest tag
spec:
  project: default
  source:
    repoURL: 'https://github.com/SidReizend/Guestbook.git'
    path: ./argo-apps
    targetRevision: main
    helm:
      valueFiles:
        - values-gbd.yaml  # Use the values.yaml that contains the destination variable
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
